### ISSUE TITLE
Research moving header from Vue to React.js

### ISSUE THREAD

**Issue by orlando** [debtcollective/dc-vue-header#14]
@orlando commented on [Wed Nov 21 2018](https://github.com/debtcollective/parent/issues/257)

The header is build using Vue, this forces us to include the Vue runtime in all the places where we need to display it, no matter if we use Vue or not.

We will start moving everything to React.js, and makes sense to have this component ready for that transition. Later on, if we need to integrate this in another framework (for example, if we want to integrate it with Discourse), we will move it to [Stencil.js](https://stenciljs.com)

## Tasks

- [x] Research migration from Vue to React.
- [x] Make a spec with the findings

## Acceptance criteria

- We have documentation on how we can migrate the header from Vue to React.

**Comment by duranmla** [comment]
I think we have already covered this right? In our [debtcollective space](https://www.notion.so/debtcollective/257-Research-moving-header-from-Vue-js-to-React-js-432ac58ef6c941579d69d1d1bd5a88c0)

**Comment by orlando** [comment]
This was implemented in https://github.com/debtcollective/header
